### ISSUE TITLE
Spring boot admin shows broken build URL

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-admin#7]
NOTE: i've also checked on jenkins. That build# does not exist even though there are also older than that build#.

![image](https://cloud.githubusercontent.com/assets/1244701/26283563/e8041576-3e33-11e7-8473-f85915ee5d82.png)

**Comment by teosarca** [comment]
nvm, it seems it was one time only... weird?!

**Comment by metas-ts** [comment]
hi @teosarca, 
currently jenkins only keeps the last 20 build jobs, plus those builds where someone pressed the "keep this build forever" button. 
Looks like this particular build job build was already removed.
What i don't know is why the ciBuildURL info is shown first for the verbui-API but not for the others..

**Comment by teosarca** [comment]
don't know either, but it's awesome that it's displayed on webui :)
